import type { Category } from "@/lib/types"

// This file contains the exact card data from the provided list with correct taglines and bullet points
export const categoriesFromList: Category[] = [
  {
    id: "mindset",
    name: "Mindset + Resilience",
    color: "#EF3F35",
    cards: [
      {
        id: "mindset-1",
        category: "Mindset + Resilience",
        title: "Momentum > Motivation",
        subtitle: "Start messy, but start.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "One small move beats no move.",
          "Clarity comes from action, not thinking.",
          "Progress compounds.",
        ],
        quote: "Action is the foundational key to all success.",
        quoteAuthor: "Pablo Picasso",
      },
      {
        id: "mindset-2",
        category: "Mindset + Resilience",
        title: "Build Calluses, Not Walls",
        subtitle: "Strength comes from the struggle.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Reframe setbacks as training, not punishment.",
          "Track small wins daily.",
          "Progress feels ugly before it looks good.",
        ],
        quote: "Strength does not come from winning. Your struggles develop your strengths.",
        quoteAuthor: "Arnold Schwarzenegger",
      },
      {
        id: "mindset-3",
        category: "Mindset + Resilience",
        title: "Resilience Is a Design Skill",
        subtitle: "Adaptation over resistance.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Treat challenges like iterative design problems.",
          "Pivot your approach, not your ambition.",
          "Version 2.0 is always stronger.",
        ],
        quote: "Fall seven times, stand up eight.",
        quoteAuthor: "Japanese proverb",
      },
      {
        id: "mindset-4",
        category: "Mindset + Resilience",
        title: "Process, Not Perfection",
        subtitle: "Build momentum without overpolishing.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Ship before you feel ready.",
          "Trust that refinement comes through reps.",
          "Perfect is the enemy of momentum.",
        ],
        quote: "Done is better than perfect.",
        quoteAuthor: "Sheryl Sandberg",
      },
      {
        id: "mindset-5",
        category: "Mindset + Resilience",
        title: "Self-Doubt Is a Signpost",
        subtitle: "Fear points toward growth.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Notice where you're hesitating.",
          "Move toward discomfort strategically.",
          "Growth always feels like risk first.",
        ],
        quote:
          "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.",
        quoteAuthor: "Vincent van Gogh",
      },
      {
        id: "mindset-6",
        category: "Mindset + Resilience",
        title: "Stay in Beta",
        subtitle: "You're a work in progress.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Think of your career as a product in active development.",
          "Iterate your mindset alongside your skills.",
          "Progress > polish.",
        ],
        quote: "If you're not embarrassed by your first launch, you launched too late.",
        quoteAuthor: "Reid Hoffman",
      },
      {
        id: "mindset-7",
        category: "Mindset + Resilience",
        title: "Zoom Out",
        subtitle: "Today's struggle isn't the whole story.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Contextualize hard days within longer arcs.",
          "Measure growth by year, not by week.",
          "Resilience is patience with ambition.",
        ],
        quote: "You can't connect the dots looking forward; you can only connect them looking backward.",
        quoteAuthor: "Steve Jobs",
      },
      {
        id: "mindset-8",
        category: "Mindset + Resilience",
        title: "Own the Frame",
        subtitle: "You decide the story.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Frame layoffs as evolution, not failure.",
          "Choose a growth narrative.",
          "Leaders are narrators, not just survivors.",
        ],
        quote: "The most powerful person in the world is the storyteller.",
        quoteAuthor: "Steve Jobs",
      },
      {
        id: "mindset-9",
        category: "Mindset + Resilience",
        title: "Energy Beats Time",
        subtitle: "Manage what fuels you, not just your hours.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Prioritize energy-generating activities.",
          "Rest isn't weakness — it's preparation.",
          "Protect peak creative windows fiercely.",
        ],
        quote: "It's not the hours you put in your work that counts, it's the work you put in the hours.",
        quoteAuthor: "Sam Ewing",
      },
      {
        id: "mindset-10",
        category: "Mindset + Resilience",
        title: "Design for Resilience, Not Fragility",
        subtitle: "Build systems that flex under pressure.",
        backgroundColor: "#B2DFDB",
        bulletPoints: [
          "Diversify your sources of learning and support.",
          "Build 'career anti-fragility' — thrive on challenge.",
          "Growth is nonlinear. Expect loops.",
        ],
        quote: "The bamboo that bends is stronger than the oak that resists.",
        quoteAuthor: "Japanese proverb",
      },
    ],
  },
  {
    id: "networking",
    name: "Networking Moves",
    color: "#2D26EB",
    cards: [
      {
        id: "networking-1",
        category: "Networking Moves",
        title: "Connections Over Applications",
        subtitle: "Build your future team now.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Reconnect with 3 former colleagues this week.",
          "Offer insight before asking for help.",
          "Conversations create opportunities, not cold emails.",
        ],
        quote: "Your network is your net worth.",
        quoteAuthor: "Porter Gale",
      },
      {
        id: "networking-2",
        category: "Networking Moves",
        title: "Conversations, Not Transactions",
        subtitle: "Focus on trust, not favors.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Approach networking as co-learning.",
          "Share something valuable before asking.",
          "Plant seeds, don't force outcomes.",
        ],
        quote: "Help others achieve their dreams and you will achieve yours.",
        quoteAuthor: "Les Brown",
      },
      {
        id: "networking-3",
        category: "Networking Moves",
        title: "Ask for Insight, Not Jobs",
        subtitle: "Curiosity unlocks more doors than desperation.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Request 20-minute insight calls.",
          "Ask about trends, skills, opportunities.",
          "Show you're thinking long-term, not panicking.",
        ],
        quote: "Seek first to understand, then to be understood.",
        quoteAuthor: "Stephen Covey",
      },
      {
        id: "networking-4",
        category: "Networking Moves",
        title: "Be Visible, Not Just Active",
        subtitle: "Let your work and ideas circulate.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Post insights or reflections weekly.",
          "Comment thoughtfully on others' work.",
          "Visibility beats silent effort.",
        ],
        quote: "You miss 100% of the shots you don't take.",
        quoteAuthor: "Wayne Gretzky",
      },
      {
        id: "networking-5",
        category: "Networking Moves",
        title: "Warm Up Dormant Ties",
        subtitle: "Old allies still matter.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Reconnect with people from past teams or projects.",
          "Share a quick update + ask about them.",
          "Dormant ties often hold hidden opportunities.",
        ],
        quote: "It's not who you know, it's who remembers you.",
        quoteAuthor: "Unknown",
      },
      {
        id: "networking-6",
        category: "Networking Moves",
        title: "Move at the Speed of Relationships",
        subtitle: "Trust builds momentum.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Nurture trust before expecting results.",
          "Follow up after conversations without expectations.",
          "Relationships move faster than résumés.",
        ],
        quote: "Trust is built with consistency.",
        quoteAuthor: "Lincoln Chafee",
      },
      {
        id: "networking-7",
        category: "Networking Moves",
        title: "Show Up Generous",
        subtitle: "Give without keeping score.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Share opportunities or connections freely.",
          "Recommend others publicly.",
          "Good karma compounds over time.",
        ],
        quote: "You can have everything you want if you just help enough people get what they want.",
        quoteAuthor: "Zig Ziglar",
      },
      {
        id: "networking-8",
        category: "Networking Moves",
        title: "Your Future Team Is Watching",
        subtitle: "Your brand is how people experience you.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Show thoughtfulness publicly and privately.",
          "Be consistent across platforms and interactions.",
          "Actions become reputation.",
        ],
        quote: "Your personal brand is what people say about you when you're not in the room.",
        quoteAuthor: "Jeff Bezos",
      },
      {
        id: "networking-9",
        category: "Networking Moves",
        title: "Plant Seeds Before You Need Them",
        subtitle: "Build before you're desperate.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Start networking when you're strong, not struggling.",
          "Relationships need time to grow.",
          "Consistency beats panic outreach.",
        ],
        quote: "The best time to plant a tree was 20 years ago. The second best time is now.",
        quoteAuthor: "Chinese Proverb",
      },
      {
        id: "networking-10",
        category: "Networking Moves",
        title: "Design Serendipity",
        subtitle: "Luck favors the visible and prepared.",
        backgroundColor: "#E6C5E6",
        bulletPoints: [
          "Share your interests and goals openly.",
          "Be discoverable across networks.",
          "Luck flows through visible networks.",
        ],
        quote: "Chance favors the prepared mind.",
        quoteAuthor: "Louis Pasteur",
      },
    ],
  },
  {
    id: "super-ic",
    name: "Being a Super IC",
    color: "#00619D",
    cards: [
      {
        id: "super-ic-1",
        category: "Being a Super IC",
        title: "Think Strategically, Build Tactically",
        subtitle: "Zoom in and zoom out with ease.",
        backgroundColor: "#E6938E",
        bulletPoints: [
          "Always connect your work to bigger goals.",
          "Deliver fast without losing sight of vision.",
          "Balance execution with systems thinking.",
        ],
        quote: "Strategy without execution is hallucination.",
        quoteAuthor: "Thomas Edison",
      },
      {
        id: "super-ic-2",
        category: "Being a Super IC",
        title: "Model the Behavior You Want to Scale",
        subtitle: "Lead without a title.",
        backgroundColor: "#E6938E",
        bulletPoints: [
          "Set the pace for collaboration.",
          "Stay humble, curious, and decisive.",
          "Influence by example, not position.",
        ],
        quote: "Leadership is action, not position.",
        quoteAuthor: "Donald H. McGannon",
      },
      {
        id: "super-ic-3",
        category: "Being a Super IC",
        title: "Own the Craft, Share the Credit",
        subtitle: "Be the gravity, not the spotlight.",
        backgroundColor: "#E6938E",
        bulletPoints: [
          "Focus on elevating the team's work.",
          "Celebrate others' wins openly.",
          "Craftsmanship earns trust faster than titles.",
        ],
        quote: "If you want to go fast, go alone. If you want to go far, go together.",
        quoteAuthor: "African Proverb",
      },
      {
        id: "super-ic-4",
        category: "Being a Super IC",
        title: "Stay Close to the Work",
        subtitle: "Craft is credibility.",
        backgroundColor: "#E6938E",
        bulletPoints: [
          "Keep designing even when leading.",
          "Show you understand the details.",
          "Staying hands-on sharpens your strategy.",
        ],
        quote: "Leaders who stay close to the work stay close to reality.",
        quoteAuthor: "Julie Zhuo",
      },
      {
        id: "super-ic-5",
        category: "Being a Super IC",
        title: "Flex Your Role, Not Your Ego",
        subtitle: "Adaptability beats seniority.",
        backgroundColor: "#E6938E",
        bulletPoints: [
          "Shift between builder and strategist as needed.",
          "Ask, 'What does the work need now?'",
          "Titles don't solve problems. People do.",
        ],
        quote: "Adaptability is about the powerful difference between adapting to cope and adapting to win.",
        quoteAuthor: "Max McKeown",
      },
    ],
  },
  {
    id: "interviewing",
    name: "Interview Gameplans",
    color: "#8A3E16",
    cards: [
      {
        id: "interviewing-1",
        category: "Interview Gameplans",
        title: "Own the Opening Minutes",
        subtitle: "Set the tone you want remembered.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Craft a 60–90 second intro story.",
          "Match your energy to your ambition.",
          "Anchor vision early, not just experience.",
        ],
        quote: "You never get a second chance to make a first impression.",
        quoteAuthor: "Will Rogers",
      },
      {
        id: "interviewing-2",
        category: "Interview Gameplans",
        title: "Frame Setbacks as Design Iterations",
        subtitle: "Narrative control is power.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Share lessons, not losses.",
          "Show how pivots made you sharper.",
          "Growth mindset beats perfect resumes.",
        ],
        quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        quoteAuthor: "Winston Churchill",
      },
      {
        id: "interviewing-3",
        category: "Interview Gameplans",
        title: "Treat Interviews Like Strategy Sessions",
        subtitle: "Be a future partner, not a petitioner.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Ask about goals, challenges, and vision.",
          "Offer ideas, not just history.",
          "Think collaboratively from minute one.",
        ],
        quote: "The best way to predict the future is to create it.",
        quoteAuthor: "Peter Drucker",
      },
      {
        id: "interviewing-4",
        category: "Interview Gameplans",
        title: "Answer With Outcomes, Not Activities",
        subtitle: "Impact beats effort.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Always close stories with measurable results.",
          "Connect your actions to business outcomes.",
          "Numbers tell stories faster than adjectives.",
        ],
        quote: "Work hard in silence, let success make the noise.",
        quoteAuthor: "Frank Ocean",
      },
      {
        id: "interviewing-5",
        category: "Interview Gameplans",
        title: "Ask Brave Questions",
        subtitle: "Curiosity signals leadership.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Ask about challenges, not just culture.",
          "Explore how success will be measured.",
          "Good questions reveal good judgment.",
        ],
        quote: "Judge a man by his questions rather than by his answers.",
        quoteAuthor: "Voltaire",
      },
      {
        id: "interviewing-6",
        category: "Interview Gameplans",
        title: "Close the Loop",
        subtitle: "End with a clear, positive signal.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Summarize your fit and excitement.",
          "Reaffirm key alignment points.",
          "Leave them remembering momentum, not mechanics.",
        ],
        quote: "How you leave them is how they remember you.",
        quoteAuthor: "Unknown",
      },
      {
        id: "interviewing-7",
        category: "Interview Gameplans",
        title: "Prepare Stories, Not Scripts",
        subtitle: "Authenticity wins attention.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Craft flexible story frameworks.",
          "Stay conversational, not mechanical.",
          "Speak like a builder, not a brochure.",
        ],
        quote: "People don't buy what you do; they buy why you do it.",
        quoteAuthor: "Simon Sinek",
      },
      {
        id: "interviewing-8",
        category: "Interview Gameplans",
        title: "Speak Their Language",
        subtitle: "Frame design wins in business terms.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Connect UX outcomes to KPIs.",
          "Translate insights into business impact.",
          "Strategy and craft must speak fluently.",
        ],
        quote: "Design is not just what it looks like and feels like. Design is how it works.",
        quoteAuthor: "Steve Jobs",
      },
      {
        id: "interviewing-9",
        category: "Interview Gameplans",
        title: "Adapt, Don't Recite",
        subtitle: "Every interview is a design sprint.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Tailor examples to company challenges.",
          "Stay flexible to shift with conversation flow.",
          "Treat interviews like prototypes, not final launches.",
        ],
        quote: "Stay committed to your decisions, but stay flexible in your approach.",
        quoteAuthor: "Tony Robbins",
      },
      {
        id: "interviewing-10",
        category: "Interview Gameplans",
        title: "Follow Up Like a Pro",
        subtitle: "Keep the momentum alive.",
        backgroundColor: "#BBDEFB",
        bulletPoints: [
          "Send a tailored thank you note within 24 hours.",
          "Reference specifics from the conversation.",
          "Remind them you're building momentum, not chasing.",
        ],
        quote: "Opportunities don't happen. You create them.",
        quoteAuthor: "Chris Grosser",
      },
    ],
  },
  {
    id: "storytelling",
    name: "Storytelling + Brand",
    color: "#B63839",
    cards: [
      {
        id: "storytelling-1",
        category: "Storytelling + Brand",
        title: "Your Story, Not Your Resume",
        subtitle: "Sell the journey, not the list.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Frame each job with Problem → Solution → Impact.",
          "Show growth arcs, not just titles.",
          "Connect your career story to future value.",
        ],
        quote: "The most powerful person in the world is the storyteller.",
        quoteAuthor: "Steve Jobs",
      },
      {
        id: "storytelling-2",
        category: "Storytelling + Brand",
        title: "Narrative Beats Chronology",
        subtitle: "Sequence matters less than story arc.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Lead with relevance, not dates.",
          "Reframe pivots as strategic learning moves.",
          "Tie chapters together with purpose, not happenstance.",
        ],
        quote: "Storytelling is the most powerful way to put ideas into the world.",
        quoteAuthor: "Robert McKee",
      },
      {
        id: "storytelling-3",
        category: "Storytelling + Brand",
        title: "Problem → Solution → Impact",
        subtitle: "Tell stories that show you in motion.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Frame your work as action, not status.",
          "Start with the problem you faced.",
          "Finish with real outcomes, not just tasks.",
        ],
        quote: "People think in stories, not statistics.",
        quoteAuthor: "Chip Heath",
      },
      {
        id: "storytelling-4",
        category: "Storytelling + Brand",
        title: "Own the Transitions",
        subtitle: "Pivots are proof of adaptability.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Frame transitions as proactive choices.",
          'Explain the "why" behind every move.',
          "Show you're intentional, not reactive.",
        ],
        quote: "Change is the essence of life; be willing to surrender who you are for what you could become.",
        quoteAuthor: "Reinhold Niebuhr",
      },
      {
        id: "storytelling-5",
        category: "Storytelling + Brand",
        title: "Build Your Signature Moves",
        subtitle: "Become known for a repeatable superpower.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Highlight 1–2 strengths you consistently deliver.",
          'Craft narratives that showcase your "signature impact."',
          "Make your value unforgettable.",
        ],
        quote: "Be so good they can't ignore you.",
        quoteAuthor: "Steve Martin",
      },
      {
        id: "storytelling-6",
        category: "Storytelling + Brand",
        title: "Signals Over Noise",
        subtitle: "Clarity beats volume.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Share fewer, sharper stories.",
          "Connect your skills to future business needs.",
          "Edit ruthlessly for focus.",
        ],
        quote: "Clarity is the elimination of mental clutter.",
        quoteAuthor: "Steve Maraboli",
      },
      {
        id: "storytelling-7",
        category: "Storytelling + Brand",
        title: "Anchor on Aspirations",
        subtitle: "Speak to where you're headed.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Frame past roles as building blocks.",
          "Show how you're evolving toward the future.",
          "Aspirations signal momentum, not stasis.",
        ],
        quote: "The best way to predict the future is to invent it.",
        quoteAuthor: "Alan Kay",
      },
      {
        id: "storytelling-8",
        category: "Storytelling + Brand",
        title: "Show the System, Not Just the Screen",
        subtitle: "Strategy and systems thinking sell seniority.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Narrate how decisions were made, not just what was built.",
          "Show you think beyond pixels.",
          "Senior hires are judged by system-level thinking.",
        ],
        quote: "Design is the body language of your strategy.",
        quoteAuthor: "Mark Levy",
      },
      {
        id: "storytelling-9",
        category: "Storytelling + Brand",
        title: "Your Brand Lives in Small Moments",
        subtitle: "Reputation is built daily.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Be consistent across conversations and content.",
          "Every meeting, post, or email shapes perception.",
          "Authenticity scales better than polish.",
        ],
        quote: "Brand is the sum of how someone feels after interacting with you.",
        quoteAuthor: "Marty Neumeier",
      },
      {
        id: "storytelling-10",
        category: "Storytelling + Brand",
        title: "Ship the Story, Not Just the Screens",
        subtitle: "Vision connects more deeply than deliverables.",
        backgroundColor: "#F0E68C",
        bulletPoints: [
          "Frame projects around the mission, not just features.",
          "Always connect back to user and business outcomes.",
          "The story makes the work matter.",
        ],
        quote: "People don't buy what you do; they buy why you do it.",
        quoteAuthor: "Simon Sinek",
      },
    ],
  },
  {
    id: "negotiation",
    name: "Offer + Negotiation",
    color: "#3B7865",
    cards: [
      {
        id: "negotiation-1",
        category: "Offer + Negotiation",
        title: "Negotiate Like a Builder",
        subtitle: "You're shaping the future, not begging for it.",
        backgroundColor: "#FFECB3",
        bulletPoints: [
          "Frame negotiations around building impact.",
          "Ask about scope, influence, and growth paths.",
          "Treat negotiation as co-design, not conflict.",
        ],
        quote: "You don't get what you deserve, you get what you negotiate.",
        quoteAuthor: "Chester Karrass",
      },
      {
        id: "negotiation-2",
        category: "Offer + Negotiation",
        title: "Scope Over Salary",
        subtitle: "Growth compounds faster than base pay.",
        backgroundColor: "#FFECB3",
        bulletPoints: [
          "Ask about team size, influence, and visibility.",
          "Bigger scope = faster career acceleration.",
          "Money follows momentum.",
        ],
        quote: "The more valuable you are, the better you are paid.",
        quoteAuthor: "Unknown",
      },
      {
        id: "negotiation-3",
        category: "Offer + Negotiation",
        title: "Ask Brave Questions",
        subtitle: "Clarity now avoids pain later.",
        backgroundColor: "#FFECB3",
        bulletPoints: [
          "Ask about decision-making power.",
          "Ask about leadership support for design.",
          "Ask about company runway and future plans.",
        ],
        quote: "The art and science of asking questions is the source of all knowledge.",
        quoteAuthor: "Thomas Berger",
      },
      {
        id: "negotiation-4",
        category: "Offer + Negotiation",
        title: "Negotiate Total Value",
        subtitle: "It's more than salary.",
        backgroundColor: "#FFECB3",
        bulletPoints: [
          "Factor in equity, bonuses, benefits, time off.",
          "Ask for learning stipends or leadership coaching.",
          "The best investments are in your growth.",
        ],
        quote: "Don't bargain yourself down before you get to the table.",
        quoteAuthor: "Carol Frohlinger",
      },
      {
        id: "negotiation-5",
        category: "Offer + Negotiation",
        title: "Slow is Smooth, Smooth is Fast",
        subtitle: "Pause to think, then respond.",
        backgroundColor: "#FFECB3",
        bulletPoints: [
          "Thank them for the offer — don't rush.",
          "Request time to review thoughtfully.",
          "Respond with strategic asks, not emotional reactions.",
        ],
        quote: "Patience is power.",
        quoteAuthor: "Venerable Sheng Yen",
      },
    ],
  },
  {
    id: "wildcards",
    name: "Power-Ups",
    color: "#6E34C8",
    cards: [
      {
        id: "wildcards-1",
        category: "Power-Ups",
        title: "Design for Serendipity",
        subtitle: "Lucky breaks happen to active builders.",
        backgroundColor: "#ABFBC5",
        bulletPoints: [
          "Share what you're exploring publicly.",
          "Connect diverse ideas boldly.",
          "Stay open to unexpected opportunities.",
        ],
        quote: "Luck is what happens when preparation meets opportunity.",
        quoteAuthor: "Seneca",
      },
      {
        id: "wildcards-2",
        category: "Power-Ups",
        title: "One Brave Move a Day",
        subtitle: "Momentum thrives on courage.",
        backgroundColor: "#ABFBC5",
        bulletPoints: [
          "Do one thing that scares you every day.",
          "Reach out, speak up, or ship something.",
          "Bravery compounds faster than strategy alone.",
        ],
        quote: "Everything you want is on the other side of fear.",
        quoteAuthor: "Jack Canfield",
      },
      {
        id: "wildcards-3",
        category: "Power-Ups",
        title: "Nobody Knows What They're Doing",
        subtitle: "Courage is pretending until you're ready.",
        backgroundColor: "#ABFBC5",
        bulletPoints: [
          'Stop waiting for "readiness."',
          "Move toward the hard thing anyway.",
          "Confidence grows by action, not affirmation.",
        ],
        quote: "Start before you're ready.",
        quoteAuthor: "Steven Pressfield",
      },
      {
        id: "wildcards-4",
        category: "Power-Ups",
        title: "Create Before You Consume",
        subtitle: "Production builds energy.",
        backgroundColor: "#ABFBC5",
        bulletPoints: [
          "Make before you scroll.",
          "Ship something, however small.",
          "Creating shifts you from passive to active instantly.",
        ],
        quote: "Energy flows where attention goes.",
        quoteAuthor: "Tony Robbins",
      },
      {
        id: "wildcards-5",
        category: "Power-Ups",
        title: "Celebrate Tiny Wins",
        subtitle: "Micro-momentum builds macro-success.",
        backgroundColor: "#ABFBC5",
        bulletPoints: [
          "Track wins, not just big milestones.",
          "Reward effort, not just outcomes.",
          "Confidence is built brick by brick.",
        ],
        quote: "Success is the sum of small efforts repeated day in and day out.",
        quoteAuthor: "Robert Collier",
      },
    ],
  },
]

export default categoriesFromList
